name=DevLab_ICM20948
version=1.0.3
author=7Semi, Jonathan Mejorado Lopez
maintainer=Jonathan Mejorado Lopez<ventas@uelectronics.com>
sentence=Arduino library for the 9-axis ICM20948 IMU (Accel + Gyro + Magnetometer)
paragraph=Lightweight and efficient driver for ICM20948 with support for I2C and SPI communication, accelerometer, gyroscope, magnetometer (AK09916), configurable filters, sample rates, and power management.
category=Sensors
url=https://github.com/UNIT-Electronics-MX/unit_devlab_icm20948_library
architectures=*
includes=DevLab_ICM20948.h
