name=7Semi_ICM20948
version=1.0.0
author=7Semi
maintainer=7Semi
sentence=Arduino library for the 9-axis ICM20948 IMU (Accel + Gyro + Magnetometer)
paragraph=Lightweight and efficient driver for ICM20948 with support for I2C and SPI communication, accelerometer, gyroscope, magnetometer (AK09916), configurable filters, sample rates, and power management.
category=Sensors
url=https://github.com/7semi-solutions/7Semi_ICM20948_Arduino-Library
architectures=*
includes=7Semi_ICM20948.h
